name: Run fetch_newsdata.R on demand

on:
  workflow_dispatch:  # Allows the workflow to be run on demand

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup R environment
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.2'  # Adjust to your R version if needed

    - name: Install R package dependencies
      run: |
        Rscript -e 'if (!requireNamespace("devtools", quietly = TRUE)) install.packages("devtools")'
        Rscript -e 'devtools::install_deps(dependencies = TRUE)'

    - name: Run fetch_newsdata.R script
      run: |
        # Run the R script and save the output as a JSON file
        Rscript fetch_newsdata.R > output.json
        today=$(date +'%Y-%m-%d')
        mkdir -p data
        mv output.json data/${today}.json

    - name: Commit and push JSON output
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add data/${today}.json
        git commit -m "Add news data JSON for ${today}"
        git push
      env:
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}  # Use GitHub token for authentication
